const PlantsData=[
    {Name:"Jade Mini Bonsai",Image:"../Assets/Images/indoorplant/Ip1.webp",Price:249,Categories:"IndoorPlant"},
    {Name:"Peace Lily Plant",Image:"../Assets/Images/indoorplant/Ip2.webp",Price:449,Categories:"IndoorPlant"},
    {Name:"Jade Plant Mini",Image:"../Assets/Images/indoorplant/Ip3.webp",Price:129,Categories:"IndoorPlant"},
    {Name:"Bamboo Palm Plant",Image:"../Assets/Images/indoorplant/Ip4.webp",Price:429,Categories:"IndoorPlant"},
    {Name:"Broken Heart Plant",Image:"../Assets/Images/indoorplant/Ip5.webp",Price:349,Categories:"IndoorPlant"},
    {Name:"Money Plant Golden",Image:"../Assets/Images/indoorplant/Ip6.webp",Price:149,Categories:"IndoorPlant"},
    {Name:"Lucky Bamboo Plant",Image:"../Assets/Images/indoorplant/Ip7.webp",Price:249,Categories:"IndoorPlant"},   
    {Name:"Spider Plant",Image:"../Assets/Images/indoorplant/Ip8.webp",Price:549,Categories:"IndoorPlant"},
    {Name:"Rubber Plant",Image:"../Assets/Images/indoorplant/Ip9.webp",Price:169,Categories:"IndoorPlant"},
    {Name:"English Ivy Variegated In Hanging Planter",Image:"../Assets/Images/hangingplant/Hp1.webp",Price:249,Categories:"HangingPlant"},
    {Name:"Money Plant Golden With Hanging Pot",Image:"../Assets/Images/hangingplant/Hp2.webp",Price:569,Categories:"HangingPlant"},
    {Name:"Money Plant N Joy With Hanging Pot",Image:"../Assets/Images/hangingplant/Hp3.webp",Price:200,Categories:"HangingPlant"},
    {Name:"Money Plant Variegated With Hanging Pot",Image:"../Assets/Images/hangingplant/Hp4.webp",Price:260,Categories:"HangingPlant"},
    {Name:"Peperomia Green Creeper With Hanging Planter",Image:"../Assets/Images/hangingplant/Hp5.webp",Price:300,Categories:"HangingPlant"},
    {Name:"Philodendron Broken Heart With Hanging Pot",Image:"../Assets/Images/hangingplant/Hp6.webp",Price:269,Categories:"HangingPlant"},
    {Name:"Spider Plant With Hanging Pot",Image:"../Assets/Images/hangingplant/Hp7.webp",Price:549,Categories:"HangingPlant"},
    {Name:"String Of Bananas",Image:"../Assets/Images/hangingplant/Hp8.webp",Price:249,Categories:"HangingPlant"},
    {Name:"Wandering Jew With Hanging Pot",Image:"../Assets/Images/hangingplant/Hp9.webp",Price:449,Categories:"HangingPlant"},
    {Name:"Aglaonema Manila Beauty - XL",Image:"../Assets/Images/OutdoorPlant/Op1.webp",Price:500,Categories:"OutdoorPlant"},
    {Name:"Ajwain Plant",Image:"../Assets/Images/OutdoorPlant/Op2.webp",Price:249,Categories:"OutdoorPlant"},
    // {Name:"Aloe Vera Plant",Image:"../Assets/Images/Outdoor plant/Op3.webp",Price:149,Categories:"OutdoorPlant"},
    {Name:"Aralia Golden Variegated",Image:"../Assets/Images/OutdoorPlant/Op4.webp",Price:369,Categories:"OutdoorPlant"},
    {Name:"Aralia Variegated Mini Plant",Image:"../Assets/Images/OutdoorPlant/Op5.webp",Price:258,Categories:"OutdoorPlant"},
    {Name:"Aralia Variegated White Plant",Image:"../Assets/Images/OutdoorPlant/Op6.webp",Price:698,Categories:"OutdoorPlant"},
    // {Name:"Betel Leaf Plant",Image:"../Assets/Images/Outdoor plant/Op7.webp",Price:149,Categories:"OutdoorPlant"},
    // {Name:"Crassula Ovata Variegated",Image:"../Assets/Images/Outdoor plant/Op8.webp",Price:149,Categories:"OutdoorPlant"},
    // {Name:"Button Fern Plant",Image:"../Assets/Images/Outdoor plant/Op9.webp",Price:149,Categories:"OutdoorPlant"},
    {Name:"JackFruit Plant",Image:"../Assets/Images/FruitPlant/Fp1.webp",Price:456,Categories:"FruitPlant"},
    {Name:"Black Plum",Image:"../Assets/Images/FruitPlant/Fp2.webp",Price:267,Categories:"FruitPlant"},
    {Name:"Fig Plant",Image:"../Assets/Images/FruitPlant/Fp3.webp",Price:357,Categories:"FruitPlant"},
    {Name:"Lemon Plant",Image:"../Assets/Images/FruitPlant/Fp4.webp",Price:459,Categories:"FruitPlant"},
    {Name:"Orange Plant",Image:"../Assets/Images/FruitPlant/Fp5.webp",Price:753,Categories:"FruitPlant"},
    {Name:"Tamerind Plant",Image:"../Assets/Images/FruitPlant/Fp6.webp",Price:951,Categories:"FruitPlant"},
    {Name:"Christmas Cactus",Image:"../Assets/Images/FloweringPlant/p1.webp",Price:249,Categories:"FloweringPlant"},
    {Name:"Kalanchoe Plant - Pink",Image:"../Assets/Images/FloweringPlant/p2.webp",Price:360,Categories:"FloweringPlant"},
    {Name:"Ixora (Rugmini) Plant - Orange",Image:"../Assets/Images/FloweringPlant/p3.webp",Price:850,Categories:"FloweringPlant"},
    {Name:"Ixora (Rugmini) Plant - Red",Image:"../Assets/Images/FloweringPlant/p4.webp",Price:469,Categories:"FloweringPlant"},
    {Name:"Kalanchoe Plant - Red",Image:"../Assets/Images/FloweringPlant/p5.webp",Price:743,Categories:"FloweringPlant"},
    {Name:"Ixora (Rugmini) Plant - Yellow",Image:"../Assets/Images/FloweringPlant/p6.webp",Price:984,Categories:"FloweringPlant"},
    // {Name:"Bird Of Paradise Plant",Image:"../Assets/Images/Flowering plant/p7.webp",Price:149,Categories:"FloweringPlant"},
]

export default PlantsData